" Plugins ---{{{
" PlugUpdate
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-bundler'
Plug 'thoughtbot/vim-rspec'
Plug 'vim-ruby/vim-ruby'
Plug 'christoomey/vim-tmux-navigator'
Plug 'slim-template/vim-slim'
Plug 'vifm/vifm'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'morhetz/gruvbox'
Plug 'godlygeek/tabular'
Plug 'Raimondi/delimitMate'
Plug 'itchyny/lightline.vim'
Plug 'airblade/vim-gitgutter'
Plug 'dense-analysis/ale'
Plug 'pbrisbin/vim-mkdir'
call plug#end()

" Enable built-in matchit plugin, which extends '%' functionality
runtime macros/matchit.vim

let g:rspec_command = "Dispatch bundle exec rspec -I . {spec}"

" Show hidden files
let NERDTreeShowHidden=1

" How can I open a NERDTree automatically when vim starts up if no files were specified?
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" }}}

" Basic settings ---{{{
" Leader
let mapleader = " "
let maplocalleader = " "

set backspace=2   " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set noswapfile    " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands
set modelines=0   " Disable modelines as a security precaution
set nomodeline
set foldlevelstart=0 " Fold all folders when a new file is opened
set termguicolors " support true color terminal

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" Make it obvious where 80 characters is
" highlight ColorColumn ctermbg=18
set textwidth=80
set colorcolumn=80

" Numbers
set relativenumber
set numberwidth=5

" Font
set guifont=Monoid

" GitGutter refresh
set updatetime=100

" Status line
let g:lightline = { 'colorscheme': 'gruvbox' }

" Ale (Linting)
let b:ale_fixers = {'ruby': ['rubocop', 'standardrb'], 'rust': ['rustfmt']}
let g:ale_fix_on_save = 1

" Color schemes
colorscheme gruvbox
" Enable italics, Make sure this is immediately after colorscheme
" https://stackoverflow.com/questions/3494435/vimrc-make-comments-italic
highlight Comment cterm=italic gui=italic
set background=dark    " Setting dark mode

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif
" }}}

" Mappings ---{{{
" Edit another file in the same directory as the current file
" uses expression to extract path from current file's path
noremap <Leader>e :e <C-R>=escape(expand("%:p:h"),' ') . '/'<CR>
noremap <Leader>ss :split <C-R>=escape(expand("%:p:h"), ' ') . '/'<CR>
noremap <Leader>v :vnew <C-R>=escape(expand("%:p:h"), ' ') . '/'<CR>
noremap <Leader>tt :tabnew <C-R>=escape(expand("%:p:h"), ' ') . '/'<CR>

noremap <Leader>t :call RunCurrentSpecFile()<CR>
noremap <Leader>s :call RunNearestSpec()<CR>
noremap <Leader>l :call RunLastSpec()<CR>
noremap <Leader>a :call RunAllSpecs()<CR>

noremap <C-n> :NERDTreeToggle<CR>

noremap <Leader>w :w<CR>
noremap <Leader>wq :wq<CR>
noremap <Leader>q :q<CR>

" Open fzf
noremap <Leader>p :Files<CR> 

" Don't use Ex mode, use Q for formatting
map Q gq

" Disables ---{{{
" This idea applies to any new mapping you create to replace an old one, and even to life in general.
" When you want to change a habit, make it harder or impossible to do!
inoremap <esc> <nop>
" Disables arrows in normal and insert modes
nnoremap <silent> <ESC>OA <Nop>
nnoremap <silent> <ESC>OB <Nop>
nnoremap <silent> <ESC>OC <Nop>
nnoremap <silent> <ESC>OD <Nop>
inoremap <silent> <ESC>OA <Nop>
inoremap <silent> <ESC>OB <Nop>
inoremap <silent> <ESC>OC <Nop>
inoremap <silent> <ESC>OD <Nop>
" }}}

" Normal mode ---{{{
nnoremap <Leader>vi :tabedit ~/.vimrc<CR>
nnoremap <Leader>so :source $MYVIMRC<CR>
nnoremap <Leader>u vawU
nnoremap <Leader>d ddO
nnoremap <Leader>, 0w
nnoremap <Leader>. $
nnoremap <Leader>o o<esc>
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l
nnoremap <Leader>ddf :call delete(expand('%'))<cr>
nnoremap <Leader><space> :noh<cr>
nnoremap <Leader>ac :tabnew app/controllers/application_controller.rb<cr>
nnoremap <Leader>um :tabnew app/models/user.rb<cr>
" }}}

" Visual mode ---{{{
vnoremap <Leader>" <esc>`<i"<esc>`>a"<esc>
" Copy to clipboard
vnoremap <Leader>z :w !pbcopy<CR>

" Alignments 
vnoremap <Leader>= :Tab /=<CR> 
vnoremap <Leader>: :Tab /:\zs<CR> 
" }}}

" Insert mode ---{{{
inoremap jk <esc>
inoremap kj <esc>
inoremap jj <esc>
inoremap kk <esc>
inoremap <c-d> <esc>ddi
inoremap <c-u> <esc>vawUea
inoremap <c-o> <esc>o
" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" Tab completion
" will insert tab at beginning of line,
" will use completion if not at beginning
set wildmode=list:longest,list:full
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<Tab>"
    else
        return "\<C-p>"
    endif
endfunction
inoremap <Tab> <C-r>=InsertTabWrapper()<CR>
inoremap <S-Tab> <C-n>
" }}}

" Movement mappings ---{{{
onoremap p i(
onoremap in( :<c-u>normal! f(vi(<cr>
onoremap il( :<c-u>normal! F)vi(<cr>
onoremap in{ :<c-u>normal! f{vi{<cr>
onoremap il{ :<c-u>normal! F}vi{<cr>
" }}}
" }}}

" Abbreviations ---{{{
iabbrev ccc context 'when' do<left><left><left><left>
iabbrev ccm context '#' do<left><left><left><left>
iabbrev ddd describe '' do<left><left><left>
iabbrev bbefore before(:each) do<enter>
iabbrev bpry binding.pry jj
" }}}

" Autocommands ---{{{
augroup filetype_ruby
  autocmd!
  autocmd FileType ruby :iabbrev <buffer> sscope scope :, -> {}<left>
  autocmd FileType ruby :iabbrev <buffer> rr return 
  autocmd FileType ruby :iabbrev <buffer> rrspec require 'rails_helper'<enter><enter>RSpec.describe
  autocmd FileType ruby :iabbrev <buffer> before(:each) "Ah ah ah, you didn't say the magic word"
augroup END
augroup filetype_html
  autocmd!
  autocmd BufWritePre,BufRead *.html :normal gg=G
augroup END

" Vimscript file settings ---{{{
augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END
" }}}

" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if line("'\"") >= 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

else

  set autoindent		" always set autoindenting on

endif " has("autocmd")
" }}}

" Commands ---{{{
command! Q q " Bind :Q to :q
command! Qall qall
command! QA qall
command! E e
command! W w
command! Wq wq

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif
" }}}

" Silver Searcher ---{{{
" Use The Silver Searcher https://github.com/ggreer/the_silver_searcher
if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in fzf for listing files. Lightning fast and respects .gitignore
  let $FZF_DEFAULT_COMMAND = 'ag --literal --files-with-matches --nocolor --hidden -g ""'

  if !exists(":Ag")
    command -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
    nnoremap \ :Ag<SPACE>
  endif
endif

" Make CtrlP use ag for listing the files. Way faster and no useless files.
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
let g:ctrlp_use_caching = 1
" }}}
