require("plugins-setup") -- needs to be at the top
require("core.settings")
require("core.keymaps")
require("plugins.nvim-tree")
require("plugins.nvim-cmp")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.leap")
require("plugins.neotest")
require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
require("plugins.lsp.null-ls")
